# Generated by Django 2.2.1 on 2019-06-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Course_Name', models.CharField(max_length=100)),
                ('Duration', models.CharField(max_length=3)),
                ('Fee', models.CharField(max_length=10)),
                ('Reg_amt', models.CharField(max_length=10)),
                ('Institute_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_management.SignUp')),
            ],
        ),
    ]
