# Generated by Django 2.2.1 on 2019-06-26 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0002_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Phone', models.IntegerField(max_length=10)),
                ('Reference', models.CharField(max_length=50)),
                ('Enquired_For', models.CharField(max_length=50)),
                ('Institute_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_management.SignUp')),
            ],
        ),
    ]
