# Generated by Django 2.2.1 on 2019-06-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0003_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Date',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Phone',
            field=models.IntegerField(),
        ),
    ]
