# Generated by Django 2.2.1 on 2019-06-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0004_auto_20190626_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Phone',
            field=models.CharField(max_length=20),
        ),
    ]
