# Generated by Django 2.2.1 on 2019-06-26 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0005_auto_20190626_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=50)),
                ('F_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=200)),
                ('Qualification', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=20)),
                ('DOB', models.CharField(max_length=20)),
                ('Course_Name', models.CharField(max_length=30)),
                ('Fee', models.CharField(max_length=20)),
                ('Duration', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='photos')),
                ('Identity', models.ImageField(upload_to='identity')),
                ('Institute_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_management.SignUp')),
            ],
        ),
    ]
