# Generated by Django 2.2.1 on 2019-06-27 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0006_admission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=30)),
                ('Amount', models.CharField(max_length=50)),
                ('Course', models.CharField(max_length=30)),
                ('Institute_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_management.SignUp')),
            ],
        ),
    ]
