# Generated by Django 2.2.1 on 2019-06-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institute_management', '0009_auto_20190627_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='photo',
            field=models.ImageField(upload_to='media/photos'),
        ),
    ]
